config/routes.rb
IsItFeasible::Application.routes.draw do
	resources :reviews
	resources :proposals

	devise_for :users, :path => "auth", :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :registration => 'register', :sign_up => 'cmon_let_me_in' }

	authenticate :user do
		root :to => 'proposals#index', as: :authenticated_user
	end

	root :to => 'auth#login'
end

app/models/proposal.rb
# Class proposals exists to store the appropriate data for proposals of business students
class Proposal < ActiveRecord::Base
	# A proposal has many reviews, but belongs to a user
	has_many :reviews
	belongs_to :user

	attr_accessible :title, :summary, :body, :score, :user_id, :created_at, :updated_at

 	# Check if proposal has reviews associated with it
 	#
 	# Parameters: Proposal ID
 	#
 	# Returns: True if there are reviews for the proposal
 	# Returns: False if there are no reviews for the proposal
	def has_reviews?(proposal_id)
		return (Review.find_all_by_proposal_id(proposal_id).count > 0)
	end

	# Get reviews associate with a proposal
	#
	# Parameters: Proposal ID
	#
	# Returns: Hash with reviews
	def get_reviews(proposal_id)
		return Review.find_all_by_proposal_id(proposal_id)
	end	
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
  # Verify a user is logged in before granting them access to view proposals
  before_filter :authenticate_user!

  # Method to show all proposals in the view
  # If user is business only show the proposals owned by the user
  # If user is engineering shows all proposals
  def index
    if current_user.major == "Business"
      @proposals = Proposal.find_all_by_user_id(current_user.id)
    else
      @proposals = Proposal.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @proposals }
    end
  end

  # Method to show specifci proposal
  #
  # If user is business user, redirect to root if they don't own it
  # If engineering user, just renders page
  # If proposal doesn't exist, then redirect to root
  def show
    @proposal = Proposal.find(params[:id])

    if current_user.major == "Business" and @proposal.user_id != current_user.id
      redirect_to root_path, :alert => "Access Denied"
    end

    if @proposal == nil
      redirect_to root_path, :alert => "No such proposal"
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @proposal }
    end
  end

  # Method to create new proposal
  # Validates user signed in and business user
  #
  # If validation fails, redirects to root
  def new
    if user_signed_in? and ( current_user.major == "Business" )
      @proposal = Proposal.new

      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @proposal }
      end
    else
      redirect_to root_path, :alert => "Access Denied"
    end
  end

  # Method to render edit form for a specfic proposal
  #
  # Parameters: proposal id
  #
  # Validates user is logged in and the proposal belongs to the user
  # If validation fails, redirects to root
  def edit
    @proposal = Proposal.find(params[:id])
    if user_signed_in? and ( current_user.major == "Business" ) and ( @proposal.user_id == current_user.id )
      @proposal
    else
      redirect_to root_path, :alert => "Access Denied"
    end
  end

  # Method to create new proposal
  #
  # Validates user signed in and business user
  # If validation fails, redirects to root
  def create
    if user_signed_in? and ( current_user.major == "Business" )
      @proposal = Proposal.create!(params[:proposal])

      respond_to do |format|
        if @proposal.save
          format.html { redirect_to @proposal, notice: 'Proposal was successfully created.' }
          format.json { render json: @proposal, status: :created, location: @proposal }
        else
          format.html { render action: "new" }
          format.json { render json: @proposal.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to root_path, :alert => "Access Denied"
    end
  end

  # Method to render update form for a specfic proposal
  #
  # Parameters: Proposal ID
  #
  # Validates user is logged in and the proposal belongs to the user
  # If validation fails, redirects to root
  def update
    @proposal = Proposal.find(params[:id])

    if user_signed_in? and ( current_user.major == "Business" ) and ( @proposal.user_id == current_user.id )
      respond_to do |format|
        if @proposal.update_attributes(params[:proposal])
          format.html { redirect_to @proposal, notice: 'Proposal was successfully updated.' }
          format.json { head :ok }
        else
          format.html { render action: "edit" }
          format.json { render json: @proposal.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to root_path, :alert => "Access Denied"
    end  
  end

  # Method to delete proposal
  # 
  # Parameters: Proposal ID
  #
  # Verifies user is logged in and owns proposal
  # If verification fails, redirects to root
  def destroy
    @proposal = Proposal.find(params[:id])
    if user_signed_in? and ( current_user.major == "Business" ) and ( @proposal.user_id == current_user.id )
      @proposal.destroy
    else
      redirect_to root_path, :alert => "Access Denied"
    end

    respond_to do |format|
      format.html { redirect_to proposals_url }
      format.json { head :ok }
    end
  end
end

app/helpers/proposals_helper.rb
module ProposalsHelper
	# Method to check if a proposal has review or not
	# 
	# Parameters: Proposal ID
	# 
	# Returns: True if review(s) exist
	# Returns: False if there are no reviews
	def has_reviews?(proposal_id)
		Review.find(proposal_id).count > 0
  	end

  	# Method to validate current user own proposal and therefore has
  	# rights to modify/delete proposal
  	#
  	# Parameters: Proposal User ID
  	#
  	# Returns: True if user owns proposal
  	# Returns: False if user doesn't own
  	def user_is_owner_of_proposal?(proposal_user_id)
  		user_signed_in? && (proposal_user_id == current_user.id)
  	end
end

app/views/proposals/_form.html.erb
<%= form_for(@proposal) do |f| %>
    <% if @proposal.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@proposal.errors.count, "error") %> prohibited this proposal from being saved:</h2>

        <ul>
        <% @proposal.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <%= hidden_field(:proposal, :user_id, :value => current_user.id) %>
    <%= hidden_field(:proposal, :score, :value => 0) %>

    <div class="field">
      <%= f.label :title %><br />
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :summary %><br />
      <%= f.text_field :summary %>
    </div>
    <div class="field">
      <%= f.label :body %><br />
      <%= f.text_field :body %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/proposals/_new_review.html.erb
<%= form_for(@review) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :proposal_id %><br />
    <%= f.number_field :proposal_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_field :comment %>
  </div>
  <div class="field">
    <%= f.label :rating %><br />
    <%= f.number_field :rating %>
  </div>
  <div class="field">
    <%= f.label :plausible_language %><br />
    <%= f.text_field :plausible_language %>
  </div>
  <div class="field">
    <%= f.label :user_interested %><br />
    <%= f.check_box :user_interested %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/proposals/edit.html.erb
<h1>Editing proposal</h1>

<%= render 'form' %>

<%= link_to 'Show', @proposal %> |
<%= link_to 'Back', proposals_path %>

app/views/proposals/index.html.erb
<h1>Listing proposals</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Summary</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @proposals.each do |proposal| %>
  <tr>
    <td><%= proposal.title %></td>
    <td><%= proposal.summary %></td>
    <td><%= link_to 'Show Proposal', proposal %></td>
    <%# If current user isn't business, don't show edit and delete links %>
    <% if (current_user.major == "Business") %>
      <td><%= link_to 'Edit Proposal', edit_proposal_path(proposal) %></td>
      <td><%= link_to 'Destroy Proposal', proposal, confirm: 'Are you sure?', method: :delete %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />

<%# If user is busesines user, allow creation of proposal via link.
Otherwise, do not show create proposal link %>
<% if (current_user.major == "Business") %>
  <%= link_to 'New Proposal', new_proposal_path %>
<% end %>

app/views/proposals/new.html.erb
<h1>New proposal</h1>

<%= render 'form' %>

<%= link_to 'Back', proposals_path %>

app/views/proposals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @proposal.title %>
</p>

<p>
  <b>Summary:</b>
  <%= @proposal.summary %>
</p>

<p>
  <b>Body:</b>
  <%= @proposal.body %>
</p>

<%# If current user is the owner of the proposal, then show modify and delete links %>
<% if user_is_owner_of_proposal?(@proposal.user_id) %>
  <%= link_to 'Edit', edit_proposal_path(@proposal) %>
  <%= link_to 'Delete', @proposal, confirm: 'Are you sure?', method: :delete %></p>
<% end %>

<h3>Reviews</h3>
<div id="reviews">
<% if @proposal.has_reviews?(@proposal.id) %>
  <% @proposal.get_reviews(@proposal.id).each do |review| %>
    <p><strong>Rating: </strong><%= review.rating %></p>
    <p><strong>Plausible Language: </strong><%= review.plausible_language %></p>
    <p><strong>Comment: </strong><%= review.comment %></p>
    <%# If the current user owns the review show the modify and delete links %>
    <% if user_is_owner_of_review?(review.user_id) %>
      <p><%= link_to 'Edit Review', edit_review_path(review) %>
      <%= link_to 'Delete Review', review, confirm: 'Are you sure?', method: :delete %></p>
    <% end %>
  <% end %>
<% else %>
  There are no reviews for this proposal.
<% end %>

<%# If the current user is an engineering major and the user hasn't created a review for this
proposal, then show the link the user to add a review %>
<p><% if (current_user.major == "Engineering") && (user_has_no_review_here(@proposal.id)) %>
  <%= link_to "Add Review", new_review_path(:proposal_id => @proposal.id ) %>
   |
<% end %>

<%= link_to 'Back', proposals_path %></p>

</div>