config/routes.rb
IsItFeasible::Application.routes.draw do
	resources :reviews
	resources :proposals

	devise_for :users, :path => "auth", :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :registration => 'register', :sign_up => 'cmon_let_me_in' }

	authenticate :user do
		root :to => 'proposals#index', as: :authenticated_user
	end

	root :to => 'auth#login'
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  # Requires any method call to be made by an engineering user if called directly
  before_filter :require_user_to_be_engineering!

  # Method to get list of reviews
  # Index of reviews only return for engineering students
  # Reviews returned are only those written by the engineering student user
  def index
    if user_signed_in? and ( current_user.major == "Engineering" )
      @reviews = Review.find_all_by_user_id(current_user.id)
    else
      redirect_to root_path, :alert => "Access Denied"
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reviews }
    end
  end

  # Method to show individual review
  # No protection on this method, when not paired to a proposal
  # Review has no meaning
  # Parameters: review id
  # Returns: single review
  def show
    @review = Review.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @review }
    end
  end

  # Method to get a hash of reviews by the proposal id
  # Paremeters: proposal id
  # Returns: hash of reviews
  def get_reviews
    @review = Review.find(params[:proposal_id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @review }
    end
  end

  # Method to create new review
  # Renders form by default
  def new
    @review = Review.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @review }
    end
  end

  # Method to call edit on review
  # Renders form
  # Validates calling user owns review
  def edit
    @review = Review.find(params[:id])
    
    if current_user.id == @review.user_id
      @review
    else
      redirect_to root_path, :alert => "Access Denied"
    end
  end

  # Method to create new revies
  # Renders form
  def create
    @review = Review.new(params[:review])

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render json: @review, status: :created, location: @review }
      else
        format.html { render action: "new" }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # Method to call update on review
  # Renders form
  # Validates calling user owns review
  def update
    @review = Review.find(params[:id])

    if current_user.id == @review.user_id
      respond_to do |format|
      if @review.update_attributes(params[:review])
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end

    else
      redirect_to root_path, :alert => "Access Denied"
    end 
  end

  # Method to delete review
  # Validates user is owner of review
  # If validation fails, redirects to root
  def destroy
    @review = Review.find(params[:id])

    if current_user.id == @review.user_id
      @review.destroy

      respond_to do |format|
        format.html { redirect_to reviews_url }
        format.json { head :ok }
      end
    else
      redirect_to root_path, :alert => "Access Denied"
    end  
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
    # Method to validate user is owner of review and therefore has
    # permissions to modify/delete
    #
    # Parameters: Proposal ID
    # 
    # Returns: True if review(s) exist
    # Returns: False if there are no reviews
  	def user_is_owner_of_review?(review_user_id)
  		user_signed_in? && (review_user_id == current_user.id)
  	end

  	# Function searches to determine if user has already written a review
  	# for the current proposal
  	#
  	# Parameters: Proposal ID
  	#
  	# Returns 'false' if user has already written a review
  	# Returns 'true' if user hasn't written a review yet
  	def user_has_no_review_here(proposal_id)
  		has_review = true
     	Review.find_all_by_proposal_id(proposal_id).each do |review|
     		if review.user_id == current_user.id
     			has_review = false
     		end
     	end
     	has_review
  	end
end

app/views/reviews/_form.html.erb
<%= form_for(@review) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= hidden_field(:review, :proposal_id, :value => params[:proposal_id]) %>
  <%= hidden_field(:review, :user_id, :value => current_user.id) %>

  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_field :comment %>
  </div>
  <div class="field">
    <%= f.label :rating %><br />
    <%= f.select :rating, options_for_select(["5", "4", "3", "2", "1"])%>
  </div>
  <div class="field">
    <%= f.label :plausible_language %><br />
    <%= f.text_field :plausible_language %>
  </div>
  <div class="field">
    <%= f.label :user_interested %><br />
    <%= f.check_box :user_interested %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/_review.html.erb
<%= div_for(review) do %>
<h4><%= review.user_id %></h4>
<%= simple_format(review.comment) %>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing review</h1>

<%= render 'form' %>

<%= link_to 'Show Review', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<h1>Listing reviews</h1>

<table>
  <tr>
    <th>Proposal</th>
    <th>User</th>
    <th>Comment</th>
    <th>Rating</th>
    <th>Plausible Language</th>
    <th>User interested</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @reviews.each do |review| %>
  <tr>
    <td><%= review.proposal_id %></td>
    <td><%= review.user_id %></td>
    <td><%= review.comment %></td>
    <td><%= review.rating %></td>
    <td><%= review.plausible_language %></td>
    <td><%= review.user_interested %></td>
    <td><%= link_to 'Show Review', review %></td>
    <td><%= link_to 'Edit Review', edit_review_path(review) %></td>
    <td><%= link_to 'Destroy Review', review, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New review</h1>

<%= render 'form' %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Proposal:</b>
  <%= @review.proposal_id %>
</p>

<p>
  <b>User:</b>
  <%= @review.user_id %>
</p>

<p>
  <b>Comment:</b>
  <%= @review.comment %>
</p>

<p>
  <b>Rating:</b>
  <%= @review.rating %>
</p>

<p>
  <b>Plausible Language:</b>
  <%= @review.plausible_language %>
</p>

<p>
  <b>User Interested:</b>
  <%= @review.user_interested %>
</p>


<%= link_to 'Edit Review', edit_review_path(@review) %> |
<%= link_to 'Back to Proposals', proposals_path %>